bot :
  name: RecreationAssistantBot
  token: 5916701577:AAEDJ-y_aIjdhLyacaCfQwfqhVRYX8eINKY

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      settings:
        web-allow-others: false
        trace: false
      enabled: true
  datasource:
    url: jdbc:h2:file:/data/recreationAssistant
    username: test
    password: test
    driver-class-name: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    hikari:
      connection-test-query: SELECT 1
  flyway:
    user: test
    locations: filesystem:db/migration
    url: jdbc:h2:file:/data/recreationAssistan
    password: test
    schemas: public
    enabled: true
    baseline-on-migrate: true

edamam:
  app_id: e487db9a
  app_key: 731b4ebfd3231254846b6ff6ec36564d
  food_limit: 8
geocode-maps_key: f41c95e1-e9c5-4c2e-9150-49f525c0c14c

weather_api_key: 3c0f9d9a-0a34-45e8-bd32-03be462e2fdb
weather_api_key_name: X-Yandex-API-Key